<?php
return array(
    'about' => 'about/index',
    'portfolio' => 'portfolio/index',
    'services/([0-9]+)' => 'services/view/$1',
    'services' => 'services/index',
    'contacts' => 'contacts/contacts',
    'admin/portfolio/create' => 'adminPortfolio/create',
    'admin/portfolio/update/([0-9]+)' => 'adminPortfolio/update/$1',
    'admin/portfolio/delete/([0-9]+)' => 'adminPortfolio/delete/$1',
    'admin/portfolio' => 'adminPortfolio/index',
    'admin/login' => 'admin/login',
    'admin/logout' => 'admin/logout',
    'admin/services/create' => 'adminService/create',
    'admin/services/delete/([0-9]+)' => 'adminService/delete/$1',
    'admin/services/update/([0-9]+)' => 'adminService/update/$1',
    'admin/services' => 'adminService/index',
    'admin/order/update/([0-9]+)' => 'adminOrder/update/$1',
    'admin/order/delete/([0-9]+)' => 'adminOrder/delete/$1',
    'admin/order/view' => 'adminOrder/view',
    'admin/order' => 'adminOrder/index',
    'admin' => 'admin/index',
    '' => 'site/index',
);